export const WORDLIST: string[] = [
  "anchor", "apple", "arrow", "badge", "baker", "basin", "beach", "berry",
  "blade", "bloom", "board", "bonus", "booth", "bread", "brick", "brook",
  "brush", "cabin", "cable", "camel", "candy", "cargo", "cedar", "chain",
  "chalk", "charm", "chess", "cliff", "clock", "cloud", "coach", "coast",
  "comet", "coral", "crane", "crown", "crystal", "daisy", "dancer", "delta",
  "denim", "depot", "diary", "dodge", "donor", "draft", "dream", "drift",
  "drum", "dune", "eagle", "ember", "epoch", "fable", "fence", "ferry",
  "fiber", "flame", "flask", "fleet", "flint", "float", "forge", "forum",
  "frost", "fruit", "galaxy", "garden", "gate", "ghost", "ginger", "glacier",
  "globe", "glove", "grain", "grape", "grove", "guide", "guitar", "harbor",
  "haven", "hawk", "hedge", "heron", "honey", "hood", "hotel", "ice",
  "igloo", "index", "inlet", "iron", "island", "ivory", "jacket", "jade",
  "jasper", "jewel", "jungle", "karma", "kayak", "kernel", "kettle", "kite",
  "knot", "label", "ladder", "lake", "lantern", "latch", "lemon", "lever",
  "light", "lily", "linen", "lodge", "lotus", "lunar", "mango", "manor",
  "maple", "marble", "marsh", "meadow", "medal", "melon", "mesa", "metro",
  "mist", "moat", "molar", "mosaic", "motor", "mural", "nectar", "nerve",
  "noble", "north", "novel", "oasis", "olive", "omega", "onyx", "opera",
  "orbit", "otter", "outlet", "owl", "oxide", "palm", "panel", "paper",
  "parcel", "patch", "pearl", "pedal", "penny", "pepper", "piano", "pilot",
  "pixel", "plaza", "plum", "pocket", "polar", "pond", "prism", "probe",
  "pulse", "quail", "quartz", "quest", "quilt", "radar", "ranch", "rapid",
  "raven", "realm", "ridge", "river", "robin", "rodeo", "royal", "ruby",
  "saddle", "sage", "salmon", "sandy", "satin", "scout", "seal", "shelter",
  "silver", "sketch", "slate", "solar", "spark", "spice", "spring", "stamp",
  "steel", "stone", "storm", "stove", "sugar", "summit", "surge", "table",
  "tango", "temple", "thorn", "tiger", "timber", "token", "topaz", "torch",
  "tower", "trail", "tulip", "tundra", "tunnel", "turtle", "valve", "vapor",
  "vault", "velvet", "verse", "villa", "violet", "vivid", "voyage", "walnut",
  "wave", "willow", "winter", "wolf", "zenith", "acorn", "atlas", "bamboo",
  "banner", "barrel", "blanket", "bobcat", "bridge", "buffer", "candle",
  "canyon", "castle", "chimney", "cipher", "cobalt", "compass", "copper",
  "crayon", "falcon",
];
